apiVersion: v1
kind: Service
metadata:
  name: vertx-infinispan
  namespace: vertx
spec:
  selector:
    cluster: vertx-infinispan
  ports:
    - name: jgroups
      port: 7800
      protocol: TCP
  publishNotReadyAddresses: true
  clusterIP: None