spec:
  template:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - env:
            - name: FOO
              value: BAR
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"    
