spec:
  template:
    spec:
      volumes:
        - name: test-volume
          hostPath:
            path: /data
            type: Directory
      containers:
        - volumeMounts:
            - name: test-volume
              mountPath: /deployments/uploads
          securityContext:
            runAsUser: 0
