spec:
  template:
    spec:
      containers:
      - env:
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: apikeysecret
              key: apitoken
