spec:
  template:
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - volumeMounts:
            - name: task-pv-storage
              mountPath: /deployments/uploads
