spec:
  template:
    spec:
      containers:
        - env:
            - name: GREET_ENV
              valueFrom:
                configMapKeyRef:
                  name: ${name}
                  key: greet.env
