spec:
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: test-secret
#      initContainers:
#      - name: init-image
#        image: alpine:latest
#        imagePullPolicy: Always
#        resources:
#          limits:
#            cpu: 1
#            memory: 1Gi
#          requests:
#            cpu: 1
#           # memory: 1Gi
