spec:
  template:
    spec:
      initContainers:
      - name: init-image
        image: init-image:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 3
            memory: 3Gi
